name: "tofu plan"

on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  tofu_plan:
    name: "plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/GitHubOIDCRole
          aws-region: ap-northeast-1
      - name: Setup Tofu (1.8.1)
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.8.1
      - name: Format Check
        working-directory: 'iac/tofu/environments/${{ inputs.environment }}/'
        run: tofu fmt -check -recursive -diff

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          tflint_version: "latest"
      - name: Init TFLint
        working-directory: 'iac/tofu/environments/${{ inputs.environment }}/'
        run: tflint --init
      - name: Run TFLint
        working-directory: 'iac/tofu/environments/${{ inputs.environment }}/'
        run: tflint

      - name: Tofu Init
        working-directory: 'iac/tofu/environments/${{ inputs.environment }}/'
        run: tofu init
      - name: Tofu Plan (${{ inputs.environment }})
        working-directory: 'iac/tofu/environments/${{ inputs.environment }}/'
        run: tofu plan

